package com.ai.ssa.web.common.mapper;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.ai.ssa.web.common.model.umps.UpmsPlugin;
import com.ai.ssa.web.common.model.umps.UpmsPluginExample;

public interface UpmsPluginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_plugin
     *
     * @mbggenerated
     */
    int countByExample(UpmsPluginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_plugin
     *
     * @mbggenerated
     */
    int deleteByExample(UpmsPluginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_plugin
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Map record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_plugin
     *
     * @mbggenerated
     */
    int insert(UpmsPlugin record);
    int insertByMap(Map record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_plugin
     *
     * @mbggenerated
     */
    int insertSelective(UpmsPlugin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_plugin
     *
     * @mbggenerated
     */
    List<UpmsPlugin> selectByExample(UpmsPluginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_plugin
     *
     * @mbggenerated
     */
    UpmsPlugin selectByPrimaryKey(UpmsPlugin pluginId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_plugin
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UpmsPlugin record, @Param("example") UpmsPluginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_plugin
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UpmsPlugin record, @Param("example") UpmsPluginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_plugin
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UpmsPlugin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_plugin
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UpmsPlugin record);

    int insertPermission(UpmsPlugin upmsPlugin);

    int deletePermissionByPlugin(Map params);

    UpmsPlugin selectPermissionByPrimaryKey(UpmsPlugin upmsPlugin);

    void updatePermissionByPrimaryKeySelective(UpmsPlugin upmsPlugin);
}