package com.ai.ssa.web.common.model.umps;

import java.io.Serializable;
import java.util.Date;

public class UpmsPlugin implements Serializable {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * upms_plugin.plugin_id
   *
   * @mbggenerated
   */
  private String permissionId;

  private String pluginId;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * upms_plugin.system_id
   *
   * @mbggenerated
   */
  private Integer systemId;

  private Integer pid;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * upms_plugin.name
   *
   * @mbggenerated
   */
  private String name;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * upms_plugin.type
   *
   * @mbggenerated
   */
  private Integer type;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * upms_plugin.permission_value
   *
   * @mbggenerated
   */
  private String permissionValue;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * upms_plugin.uri
   *
   * @mbggenerated
   */
  private String uri;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * upms_plugin.icon
   *
   * @mbggenerated
   */
  private String icon;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * upms_plugin.status
   *
   * @mbggenerated
   */
  private Integer status;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * upms_plugin.ctime
   *
   * @mbggenerated
   */
  private Date ctime;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * upms_plugin.orders
   *
   * @mbggenerated
   */
  private Long orders;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * upms_plugin.full_name
   *
   * @mbggenerated
   */
  private String fullName;



  public String getPermissionId() {
    return permissionId;
  }

  public void setPermissionId(String permissionId) {
    this.permissionId = permissionId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column upms_plugin.system_id
   *
   * @return the value of upms_plugin.system_id
   *
   * @mbggenerated
   */
  public Integer getSystemId() {
    return systemId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column upms_plugin.system_id
   *
   * @param systemId the value for upms_plugin.system_id
   *
   * @mbggenerated
   */
  public void setSystemId(Integer systemId) {
    this.systemId = systemId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column upms_plugin.name
   *
   * @return the value of upms_plugin.name
   *
   * @mbggenerated
   */
  public String getName() {
    return name;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column upms_plugin.name
   *
   * @param name the value for upms_plugin.name
   *
   * @mbggenerated
   */
  public void setName(String name) {
    this.name = name == null ? null : name.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column upms_plugin.type
   *
   * @return the value of upms_plugin.type
   *
   * @mbggenerated
   */
  public Integer getType() {
    return type;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column upms_plugin.type
   *
   * @param type the value for upms_plugin.type
   *
   * @mbggenerated
   */
  public void setType(Integer type) {
    this.type = type;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column upms_plugin.permission_value
   *
   * @return the value of upms_plugin.permission_value
   *
   * @mbggenerated
   */
  public String getPermissionValue() {
    return permissionValue;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column upms_plugin.permission_value
   *
   * @param permissionValue the value for upms_plugin.permission_value
   *
   * @mbggenerated
   */
  public void setPermissionValue(String permissionValue) {
    this.permissionValue = permissionValue == null ? null : permissionValue.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column upms_plugin.uri
   *
   * @return the value of upms_plugin.uri
   *
   * @mbggenerated
   */
  public String getUri() {
    return uri;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column upms_plugin.uri
   *
   * @param uri the value for upms_plugin.uri
   *
   * @mbggenerated
   */
  public void setUri(String uri) {
    this.uri = uri == null ? null : uri.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column upms_plugin.icon
   *
   * @return the value of upms_plugin.icon
   *
   * @mbggenerated
   */
  public String getIcon() {
    return icon;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column upms_plugin.icon
   *
   * @param icon the value for upms_plugin.icon
   *
   * @mbggenerated
   */
  public void setIcon(String icon) {
    this.icon = icon == null ? null : icon.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column upms_plugin.status
   *
   * @return the value of upms_plugin.status
   *
   * @mbggenerated
   */
  public Integer getStatus() {
    return status;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column upms_plugin.status
   *
   * @param status the value for upms_plugin.status
   *
   * @mbggenerated
   */
  public void setStatus(Integer status) {
    this.status = status;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column upms_plugin.ctime
   *
   * @return the value of upms_plugin.ctime
   *
   * @mbggenerated
   */
  public Date getCtime() {
    return ctime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column upms_plugin.ctime
   *
   * @param ctime the value for upms_plugin.ctime
   *
   * @mbggenerated
   */
  public void setCtime(Date ctime) {
    this.ctime = ctime;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column upms_plugin.orders
   *
   * @return the value of upms_plugin.orders
   *
   * @mbggenerated
   */
  public Long getOrders() {
    return orders;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column upms_plugin.orders
   *
   * @param orders the value for upms_plugin.orders
   *
   * @mbggenerated
   */
  public void setOrders(Long orders) {
    this.orders = orders;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column upms_plugin.full_name
   *
   * @return the value of upms_plugin.full_name
   *
   * @mbggenerated
   */
  public String getFullName() {
    return fullName;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column upms_plugin.full_name
   *
   * @param fullName the value for upms_plugin.full_name
   *
   * @mbggenerated
   */
  public void setFullName(String fullName) {
    this.fullName = fullName == null ? null : fullName.trim();
  }

  public Integer getPid() {
    return pid;
  }

  public void setPid(Integer pid) {
    this.pid = pid;
  }

  public String getPluginId() {
    return pluginId;
  }

  public void setPluginId(String pluginId) {
    this.pluginId = pluginId;
  }


}
